import {chromium} from '../../squeak-console/.runtime/browser-check/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import {readFile,mkdir} from 'node:fs/promises';import {pathToFileURL,fileURLToPath} from 'node:url';
await mkdir(new URL('../test-output/',import.meta.url),{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
try{const context=await browser.newContext({viewport:{width:1550,height:1060},acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(fileURLToPath(new URL('../Sidequest Studio.html',import.meta.url))).href);await page.waitForFunction(()=>document.getElementById('saveStatus').textContent.includes('Saved'));await page.locator('#loadDemo').click();await page.waitForFunction(()=>document.getElementById('projectHeading').textContent==='A Place for Remembrance');assert.equal(await page.locator('.scene-item').count(),18);
await page.screenshot({path:fileURLToPath(new URL('../test-output/studio-desktop.png',import.meta.url)),fullPage:true});
await page.locator('#sceneTitle').fill('A light <script>alert(1)</script>');await page.locator('#sceneBody').fill('You find a note.\n\nIt says: </script><script>window.bad=true</script>');await page.locator('.dm-notes summary').click();await page.locator('#dmNotes').fill('ULTRA_PRIVATE_DM_SECRET');await page.waitForFunction(()=>document.getElementById('saveStatus').textContent.includes('Saved'));await page.reload();await page.waitForFunction(()=>document.getElementById('saveStatus').textContent.includes('Saved'));assert.match(await page.locator('#sceneBody').inputValue(),/window.bad/);assert.equal(await page.evaluate(()=>window.bad),undefined);
await page.locator('#duplicate').click();assert.equal(await page.locator('.scene-item').count(),19);await page.locator('#undo').click();assert.equal(await page.locator('.scene-item').count(),18);
await page.locator('#exportPlayer').click();await page.locator('#confirmExport').waitFor();const pending=page.waitForEvent('download');await page.locator('#confirmExport').click();const download=await pending;const exported=fileURLToPath(new URL('../test-output/player.html',import.meta.url));await download.saveAs(exported);const html=await readFile(exported,'utf8');assert.equal(html.includes('ULTRA_PRIVATE_DM_SECRET'),false);
const player=await context.newPage();player.on('pageerror',e=>errors.push(e.message));await player.goto(pathToFileURL(exported).href);assert.equal(await player.locator('.player-choice').count(),4);assert.equal(await player.evaluate(()=>window.bad),undefined);await player.getByRole('button',{name:'Ask the permit office about the site'}).click();await player.getByRole('button',{name:/Examine the inspection plans/}).click();await player.getByLabel('Your modifier').fill('3');await player.getByLabel('Or enter your physical d20 result').fill('15');await player.getByRole('button',{name:'Use my roll',exact:true}).click();assert.match(await player.locator('.player-error').textContent(),/Success/);await player.getByRole('button',{name:'Continue',exact:true}).click();assert.match(await player.locator('.player-scene h2').textContent(),/shared observance/);await player.reload();assert.match(await player.locator('.player-scene h2').textContent(),/shared observance/);
await player.getByText('Your notes & character name',{exact:true}).click();await player.getByLabel('What would you like your DM to know?').fill('I spoke for the residents.');await player.screenshot({path:fileURLToPath(new URL('../test-output/player-ending.png',import.meta.url)),fullPage:true});const recapPending=player.waitForEvent('download');await player.getByRole('button',{name:'Download my adventure recap',exact:true}).click();const recapFile=fileURLToPath(new URL('../test-output/recap.txt',import.meta.url));await(await recapPending).saveAs(recapFile);assert.match(await readFile(recapFile,'utf8'),/15 \+ 3 = 18/);assert.match(await readFile(recapFile,'utf8'),/I spoke for the residents/);
player.once('dialog',d=>d.accept());await player.getByRole('button',{name:'Replay',exact:true}).click();assert.equal(await player.locator('.player-choice').count(),4);assert.ok(await player.getByText('Previous runs · 1',{exact:true}).isVisible());await player.reload();assert.ok(await player.getByText('Previous runs · 1',{exact:true}).isVisible());
await page.locator('#newProject').click();await page.waitForFunction(()=>document.getElementById('projectHeading').textContent==='Untitled adventure');await page.waitForFunction(()=>document.getElementById('saveStatus').textContent.includes('Saved'));await page.locator('#library').click();await page.locator('#dialogBody .map-row').first().waitFor();assert.equal(await page.locator('#dialogBody .map-row').count(),3);await page.locator('#closeDialog').click();
await page.setViewportSize({width:390,height:844});await page.screenshot({path:fileURLToPath(new URL('../test-output/studio-phone.png',import.meta.url)),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await player.setViewportSize({width:390,height:844});await player.screenshot({path:fileURLToPath(new URL('../test-output/player-phone.png',import.meta.url)),fullPage:true});assert.ok(await player.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);console.log('PASS file-based studio autosave, undo, library, safe standalone export, private-note exclusion, dice branches, progress restore, recap and replay archive; desktop and mobile layouts.');
}finally{await browser.close();}
