const $=id=>document.getElementById(id),make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let appMode='dm';
let project=demoAdventure(),current=project.start,db=null,undoStack=[],saveTimer,saveChain=Promise.resolve(),dirty=false,toastTimer,previewController;
const active=()=>project.scenes.find(s=>s.id===current)||project.scenes[0];
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
function checkpoint(){undoStack.push(JSON.stringify(project));if(undoStack.length>20)undoStack.shift();$('undo').disabled=false;}
function persist(){clearTimeout(saveTimer);const snapshot=structuredClone(project);snapshot.updated=new Date().toISOString();project.updated=snapshot.updated;saveChain=saveChain.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{if(!db){reject(Error('Browser storage unavailable'));return;}const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(snapshot);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Save interrupted'));})).then(()=>{if(project.id===snapshot.id&&project.updated===snapshot.updated){dirty=false;$('saveStatus').textContent='Saved on this device';}try{localStorage.setItem('sidequest-active',project.id);}catch{}return true;}).catch(e=>{$('saveStatus').textContent='Not saved · export a project file';dirty=true;toast('Local save failed. Use Save project file to keep your work.');return false;});return saveChain;}
function changed(){dirty=true;$('saveStatus').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(persist,350);renderList();$('projectHeading').textContent=project.title||'Untitled adventure';$('wordCount').textContent=(active().body.trim()?active().body.trim().split(/\s+/).length:0)+' words';}
function editField(id,key){let ready=true;$(id).onfocus=()=>ready=true;$(id).oninput=()=>{if(ready){checkpoint();ready=false;}active()[key]=$(id).value;changed();};}
for(const [id,key]of [['sceneTitle','title'],['sceneBody','body'],['imageAlt','alt'],['dmNotes','notes'],['reward','reward']])editField(id,key);
function bind(input,obj,key,numeric=false){let fresh=true;input.onfocus=()=>fresh=true;input.oninput=()=>{if(fresh){checkpoint();fresh=false;}obj[key]=numeric?Number(input.value):input.value;changed();};}
function download(name,content,type){const a=make('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function filename(){return (project.title||'Adventure').replace(/[^a-z0-9 -]/gi,'').trim().slice(0,80)||'Adventure';}
function openDialog(title){$('dialogTitle').textContent=title;$('dialogBody').replaceChildren();if(!$('dialog').open)$('dialog').showModal();return $('dialogBody');}
$('closeDialog').onclick=()=>$('dialog').close();$('dialog').addEventListener('click',e=>{if(e.target===$('dialog')){const r=$('dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('dialog').close();}});
function renderList(){const filter=$('search').value.toLowerCase();$('sceneList').replaceChildren();$('sceneCount').textContent=project.scenes.length+' scenes';project.scenes.forEach((s,i)=>{if(filter&&!`${s.title} ${s.body}`.toLowerCase().includes(filter))return;const b=make('button',undefined,'scene-item');b.dataset.scene=s.id;b.setAttribute('aria-current',String(s.id===current));const body=make('span');body.append(make('strong',s.title||'Untitled scene'),make('small',s.id===project.start?'STARTING SCENE':s.ending?'ENDING':s.choices.length+' choices'));b.append(make('span',String(i+1).padStart(2,'0'),'scene-number'),body);b.onclick=()=>{current=s.id;renderEditor();renderList();};$('sceneList').append(b);});}
function field(label,control){control.setAttribute('aria-label',label);const l=make('label',label);l.append(control);return l;}
function inputFor(obj,key,placeholder='',type='text'){const n=make('input');n.type=type;n.value=obj[key]??'';n.placeholder=placeholder;bind(n,obj,key,type==='number');return n;}
function targetSelect(choice,key){const select=make('select');select.append(new Option('Choose a destination…',''));for(const s of project.scenes)select.append(new Option((s.ending?'◇ ':'')+(s.title||'Untitled scene'),s.id));select.value=choice[key]||'';select.onchange=()=>{checkpoint();choice[key]=select.value;changed();};return select;}
function renderChoices(){const s=active();$('choicesSection').hidden=s.ending;$('endingSection').hidden=!s.ending;$('choiceList').replaceChildren();s.choices.forEach((c,i)=>{const card=make('div',undefined,'choice-card');const head=make('div',undefined,'choice-head');head.append(make('span','CHOICE '+String(i+1).padStart(2,'0')));const controls=make('div');for(const [label,delta] of [['↑',-1],['↓',1]]){const move=make('button',label);move.setAttribute('aria-label',delta<0?'Move choice up':'Move choice down');move.disabled=i+delta<0||i+delta>=s.choices.length;move.onclick=()=>{checkpoint();[s.choices[i],s.choices[i+delta]]=[s.choices[i+delta],s.choices[i]];changed();renderChoices();};controls.append(move);}const del=make('button','Remove');del.onclick=()=>{checkpoint();s.choices.splice(i,1);changed();renderChoices();};controls.append(del);head.append(controls);card.append(head,field('Button text',inputFor(c,'label','What can they do?')));const type=make('select');type.append(new Option('Story choice','choice'),new Option('D20 ability check','check'),new Option('Random event table','random'));type.value=c.type;type.onchange=()=>{checkpoint();c.type=type.value;c.dc??=12;c.modifier??=0;if(c.type==='random'){c.sides??=6;if(!c.events?.length)c.events=[{min:1,max:3,label:'',target:''},{min:4,max:6,label:'',target:''}];}changed();renderChoices();};card.append(field('Choice type',type));if(c.type==='check'){const grid=make('div',undefined,'choice-grid three');const dc=inputFor(c,'dc','','number');dc.min=1;dc.max=40;const modifier=inputFor(c,'modifier','','number');modifier.min=-30;modifier.max=30;grid.append(field('Ability / skill',inputFor(c,'skill','Perception')),field('DC',dc),field('Default modifier',modifier));card.append(grid);}if(c.type==='random'){renderRandomTable(card,c);$('choiceList').append(card);return;}const destinations=make('div',undefined,'choice-grid');destinations.append(field(c.type==='check'?'On success →':'Leads to →',targetSelect(c,'target')));if(c.type==='check')destinations.append(field('On failure →',targetSelect(c,'failure')));card.append(destinations);const create=make('button','＋ Create & link a new scene','new-target');create.onclick=()=>{checkpoint();const scene=newScene('After '+(c.label||'this choice'));project.scenes.push(scene);c.target=scene.id;changed();renderChoices();};card.append(create);const advanced=make('details');advanced.append(make('summary','Optional story flags'));advanced.append(field('Only show if player has this flag',inputFor(c,'requires','e.g. found-key')),field('Give this flag after choosing',inputFor(c,'gives','e.g. trusted-ferryman')),make('p','Flags are exact text labels. Any outcome of this choice grants its flag.','hint'));card.append(advanced);$('choiceList').append(card);});if(!s.choices.length)$('choiceList').append(make('p','Add a choice, or mark this scene as an ending.','hint'));}
function renderEditor(){renderSceneLoot();const s=active();current=s.id;$('scenePosition').textContent='SCENE '+String(project.scenes.indexOf(s)+1).padStart(2,'0');for(const [id,key]of [['sceneTitle','title'],['sceneBody','body'],['imageAlt','alt'],['dmNotes','notes'],['reward','reward']])$(id).value=s[key]||'';$('isStart').checked=s.id===project.start;$('isEnding').checked=s.ending;$('sceneImage').hidden=!s.image;$('imagePlaceholder').hidden=!!s.image;$('removeImage').hidden=!s.image;$('altLabel').hidden=!s.image;if(s.image)$('sceneImage').src=s.image;else $('sceneImage').removeAttribute('src');$('wordCount').textContent=(s.body.trim()?s.body.trim().split(/\s+/).length:0)+' words';$('undo').disabled=!undoStack.length;renderChoices();}
function renderAll(){renderModeNotice();renderList();renderEditor();$('projectHeading').textContent=project.title||'Untitled adventure';refreshPreview();}
function refreshPreview(scene){previewController=mountPlayer($('preview'),{...playerCopy(project),start:scene||project.start},{preview:true});}
$('refreshPreview').onclick=()=>refreshPreview();$('previewScene').onclick=()=>refreshPreview(current);$('search').oninput=renderList;
$('addScene').onclick=()=>{checkpoint();const s=newScene();project.scenes.push(s);current=s.id;changed();renderEditor();renderList();$('sceneTitle').focus();$('sceneTitle').select();};
$('addChoice').onclick=()=>{if(active().choices.length>=30)return toast('Use at most 30 choices per scene.');checkpoint();active().choices.push({id:uid(),label:'',type:'choice',target:'',dc:12,modifier:0});changed();renderChoices();};
$('isStart').onchange=()=>{if(!$('isStart').checked){$('isStart').checked=true;return toast('Choose Starting scene on a different scene to move the start.');}checkpoint();project.start=current;changed();};
$('isEnding').onchange=()=>{checkpoint();active().ending=$('isEnding').checked;changed();renderChoices();};
$('duplicate').onclick=()=>{checkpoint();const s=structuredClone(active()),old=s.id;s.id=uid();s.title+=' (copy)';s.choices.forEach(c=>{c.id=uid();if(c.target===old)c.target=s.id;if(c.failure===old)c.failure=s.id;for(const e of c.events||[])if(e.target===old)e.target=s.id;});project.scenes.splice(project.scenes.indexOf(active())+1,0,s);current=s.id;changed();renderEditor();renderList();};
$('deleteScene').onclick=()=>{if(project.scenes.length===1)return toast('Keep at least one scene.');const linked=project.scenes.filter(s=>s.choices.some(c=>c.target===current||c.failure===current||c.events?.some(e=>e.target===current))).length;if(!confirm(`Delete “${active().title}”? ${linked?linked+' scenes link here; those links will need fixing. ':''}You can undo this.`))return;checkpoint();project.scenes=project.scenes.filter(s=>s.id!==current);if(project.start===current)project.start=project.scenes[0].id;current=project.scenes[0].id;changed();renderAll();};
$('undo').onclick=()=>{if(!undoStack.length)return;project=JSON.parse(undoStack.pop());if(!project.scenes.some(s=>s.id===current))current=project.start;changed();renderAll();};
async function addImage(file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type))return toast('Use a PNG, JPEG or WebP image.');if(file.size>12*1024*1024)return toast('Choose an image smaller than 12 MB.');const scene=active();try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#f7f1e6';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();if(!project.scenes.includes(scene))return;checkpoint();scene.image=canvas.toDataURL('image/jpeg',.84);changed();renderEditor();toast('Image added and resized for a smaller adventure file.');}catch{toast('That image could not be opened. Try another file.');}}
$('imageFile').onchange=e=>{addImage(e.target.files[0]);e.target.value='';};$('removeImage').onclick=()=>{checkpoint();active().image='';active().alt='';changed();renderEditor();};for(const name of ['dragenter','dragover'])$('imageArea').addEventListener(name,e=>{e.preventDefault();$('imageArea').classList.add('dragging');});$('imageArea').ondragleave=()=>$('imageArea').classList.remove('dragging');$('imageArea').ondrop=e=>{e.preventDefault();$('imageArea').classList.remove('dragging');addImage(e.dataTransfer.files[0]);};document.addEventListener('paste',e=>{const file=[...e.clipboardData.items].find(i=>i.type.startsWith('image/'))?.getAsFile();if(file&&!$('dialog').open){e.preventDefault();addImage(file);}});
$('settings').onclick=()=>{const body=openDialog('Adventure details');for(const [key,title,multi] of [['title','Adventure title'],['subtitle','A one-line invitation'],['player','Player / character name'],['briefing','Before they begin',true]]){const n=make(multi?'textarea':'input');n.value=project[key]||'';n.maxLength=key==='briefing'?100000:key==='subtitle'?500:key==='player'?100:200;bind(n,project,key);body.append(field(title,n));}body.append(make('p','Explain where this sits in the campaign, which character to use, and any table rules.','hint'));};
function showIssues(){const issues=validateAdventure(project);const body=openDialog('Check your adventure');body.append(make('p',issues.length?`${issues.filter(i=>i.level==='error').length} issues to fix · ${issues.filter(i=>i.level==='warning').length} suggestions`:'All paths are linked and there is a reachable ending. Ready to export.'));for(const issue of issues){const s=project.scenes.find(s=>s.id===issue.scene);const b=make('button',(s?s.title+': ':'')+issue.message,'issue '+issue.level);b.onclick=()=>{if(s){current=s.id;renderAll();$('dialog').close();}};body.append(b);}body.append(make('p','This checks story structure, not difficulty or campaign balance. Play the preview to review the actual choices.','hint'));return issues;}
$('validate').onclick=showIssues;
function renderMapList(body){for(const s of project.scenes){const row=make('div',undefined,'map-row');const b=make('button',(s.id===project.start?'START · ':s.ending?'ENDING · ':'')+s.title);b.onclick=()=>{current=s.id;renderAll();$('dialog').close();};row.append(b);if(s.ending)row.append(make('p','◇ The story ends here.'));else for(const c of s.choices){if(c.type==='random'){for(const e of c.events||[])row.append(make('p',c.label+' · d'+c.sides+' ['+e.min+' to '+e.max+'] '+e.label+' → '+(project.scenes.find(s=>s.id===e.target)?.title||'[unlinked]')));continue;}row.append(make('p',c.label+' → '+(project.scenes.find(s=>s.id===c.target)?.title||'[unlinked]')+(c.type==='check'?' / failure → '+(project.scenes.find(s=>s.id===c.failure)?.title||'[unlinked]'):'')));}body.append(row);}}
$('outline').onclick=()=>{const body=openDialog('Turn an outline into scenes');body.append(make('p','One scene title per line. We’ll add them in order and link each to the next. The last becomes an ending. Your existing scenes stay intact.'));const text=make('textarea');text.rows=8;text.placeholder='A message at the inn\nThe abandoned mill\nA debt repaid';body.append(text);const button=make('button','Create linked scenes','primary');button.onclick=()=>{const lines=text.value.split('\n').map(x=>x.trim()).filter(Boolean);if(!lines.length)return;if(project.scenes.length+lines.length>300)return toast('Keep the project under 300 scenes.');checkpoint();const scenes=lines.map(newScene);scenes.forEach((s,i)=>{s.ending=i===scenes.length-1;if(!s.ending)s.choices=[{id:uid(),label:'Continue',target:scenes[i+1].id,type:'choice'}];});project.scenes.push(...scenes);current=scenes[0].id;changed();renderAll();$('dialog').close();};body.append(button);};
$('exportProject').onclick=()=>{download(filename()+'.sidequest.json',JSON.stringify(project,null,2),'application/json');toast('Editable project downloaded. Keep it as your backup.');};
$('importProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>40*1024*1024)return toast('Project files must be smaller than 40 MB.');try{const incoming=cleanProject(JSON.parse(await file.text()));if(!await persist())return;incoming.id=uid();project=incoming;current=project.start;undoStack=[];changed();renderAll();toast('Imported as a new library copy. Your previous adventure is still saved.');}catch(e){toast(e.message);}};
async function switchProject(p){if(!await persist())return;project=p;current=project.start;undoStack=[];$('search').value='';changed();renderAll();}
$('newProject').onclick=()=>switchProject(newAdventure());$('loadDemo').textContent='Load example adventure · 18 scenes';$('loadDemo').onclick=()=>switchProject(demoAdventure());
const library=make('button','Library');library.id='library';$('settings').before(library);library.onclick=async()=>{await persist();const body=openDialog('Saved adventures');if(!db){body.append(make('p','Browser storage is unavailable. Use project files to save and reopen adventures.'));return;}const projects=await new Promise((resolve,reject)=>{const req=db.transaction('projects').objectStore('projects').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});projects.sort((a,b)=>b.updated.localeCompare(a.updated));for(const p of projects){const row=make('div',undefined,'map-row');row.append(make('strong',p.title||'Untitled adventure'),make('p',p.scenes.length+' scenes · '+new Date(p.updated).toLocaleString()));const open=make('button',p.id===project.id?'Currently open':'Open adventure');open.disabled=p.id===project.id;open.onclick=async()=>{await switchProject(cleanProject(p));$('dialog').close();};row.append(open);body.append(row);}body.append(make('p','Saved in this browser on this device. Export project files before clearing browser data or moving to another computer.','hint'));};
$('help').onclick=()=>{const body=openDialog('Using Sidequest Studio');for(const [title,text]of [['Open on Mac or Windows','Extract Sidequest-Studio.zip into a folder you want to keep. On Mac, Control-click Sidequest Studio.html, choose Open With, then Safari, Chrome or Edge. On Windows, open the HTML with Chrome or Edge. No installation is needed. Send the ZIP to other DMs, not your localhost link.'],['Save, move and restore','Library autosaves stay in this browser. Save project file downloads an editable JSON backup. Use Open project inside DM mode to restore it on another computer. Keep using the same studio file and browser for local saves. Players reopen the same adventure file to resume, then download a recap to send back.'],['1. Add scenes','Start with the sample or a new adventure. Add scene text, images and choices. Paste an outline to build a linked sequence quickly.'],['2. Connect the paths','Every choice needs a destination. A d20 check has separate success and failure destinations. Mark the final scenes as endings.'],['3. Play it first','Try the player preview. Check adventure finds broken links and unreachable scenes. DM notes are excluded from the player export.'],['4. Send & replay','Export player adventure makes one HTML file with its images included. Send it to your player to open in a desktop browser. They can resume in the same browser, replay it, and download a recap to send back. Some email apps block HTML attachments; send a ZIP if needed.'],['Keep your work','Autosave and the Library stay in this browser. Save project file gives you an editable backup. Player HTML contains the story branches; it is not secure against a player inspecting the file. No AI or online account is required.']]){body.append(make('h3',title),make('p',text));}};
$('exportPlayer').onclick=()=>{const issues=validateAdventure(project);if(issues.some(i=>i.level==='error')){showIssues();return;}const body=openDialog('Export player adventure');body.append(make('p','The player gets a single HTML file containing the story, pictures, choices, dice checks and progress saving. Your private DM notes stay here.'));if(issues.length)body.append(make('p',issues.length+' suggestions remain. Use Check adventure to review them; export is still available.'));const b=make('button','Download player adventure','primary');b.id='confirmExport';b.onclick=()=>{const data=JSON.stringify(playerCopy(project)).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');const edition=String(hash(data));const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Solo adventure</title><style>body{margin:0;padding:32px 12px;background:#1e3027}'+PLAYER_CSS+'</style></head><body><main id="story"></main><script>'+mountPlayer.toString()+'\nmountPlayer(document.getElementById("story"),'+data+',{edition:'+JSON.stringify(edition)+'});<\/script></body></html>';download(filename()+'.html',html,'text/html;charset=utf-8');$('dialog').close();toast('Player adventure downloaded. Keep the HTML file to replay it.');};body.append(b);};
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();$('exportProject').click();}});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function boot(){try{db=await new Promise((resolve,reject)=>{const req=indexedDB.open('sidequest-studio',1);req.onupgradeneeded=()=>req.result.createObjectStore('projects',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const saved=await new Promise((resolve,reject)=>{const r=db.transaction('projects').objectStore('projects').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});let id;try{id=localStorage.getItem('sidequest-active');}catch{}const last=saved.find(p=>p.id===id)||saved.sort((a,b)=>b.updated.localeCompare(a.updated))[0];if(last)project=cleanProject(last);if(!project.example&&((project.title==='A Place for Remembrance'&&project.scenes[0]?.body.startsWith('With the twentieth anniversary'))||(project.title==='The Lantern at Lowwater'&&project.scenes[0]?.body.startsWith('The innkeeper sets a brass lantern'))))project.example=true;current=project.start;renderAll();await persist();}catch{renderAll();$('saveStatus').textContent='Use project files · browser storage unavailable';toast('Use Save project file to preserve work in this browser.');}}
boot();

function renderRandomTable(card,c){const die=make('select');for(const sides of [4,6,8,10,12,20,100])die.append(new Option('d'+sides,String(sides)));die.value=String(c.sides);die.onchange=()=>{checkpoint();c.sides=Number(die.value);changed();renderChoices();};card.append(field('Event die',die),make('p','Assign every possible roll to one event. Wider ranges make an event more likely. Changing the die keeps your rows; update their ranges as needed.','hint'));for(const [index,event] of c.events.entries()){const row=make('div',undefined,'event-row');const head=make('div',undefined,'choice-head');head.append(make('span','EVENT '+(index+1)));const remove=make('button','Remove event');remove.onclick=()=>{checkpoint();c.events.splice(index,1);changed();renderChoices();};head.append(remove);row.append(head);const range=make('div',undefined,'choice-grid');const min=inputFor(event,'min','','number'),max=inputFor(event,'max','','number');min.min=max.min=1;min.max=max.max=c.sides;range.append(field('Roll from',min),field('Through',max));row.append(range,field('Event description',inputFor(event,'label','A neighbour asks for help')),field('Continue to',targetSelect(event,'target')));card.append(row);}const add=make('button','＋ Add event');add.onclick=()=>{if(c.events.length>=100)return;checkpoint();const next=Math.min(c.sides,Math.max(0,...c.events.map(e=>e.max||0))+1);c.events.push({min:next,max:c.sides,label:'',target:''});changed();renderChoices();};card.append(add);const errors=randomErrors(c,new Set(project.scenes.map(s=>s.id)));if(errors.length)card.append(make('p','Check adventure will flag missing destinations, gaps and overlapping ranges.','hint'));card.append(make('p','Use Preview this scene to roll the table. The player can roll in the app or enter a physical die result.','hint'));}

function renderModeNotice(){$('exampleNotice').hidden=!project.example;if(project.example)$('exampleNotice').querySelector('span').textContent='This example currently has '+project.scenes.length+' scenes. '+(project.scenes.length<18?'Load the current example from the footer to see the expanded version. Your saved copy stays in the Library.':'Placeholder content only. Use Flowchart to see all branches.');}
function setMode(mode){appMode=mode;document.body.dataset.mode=mode;$('dmMode').setAttribute('aria-pressed',String(mode==='dm'));$('playerMode').setAttribute('aria-pressed',String(mode==='player'));$('playerWorkspace').hidden=mode!=='player';renderModeNotice();if(mode==='player'){const body=$('fullPlayer');const errors=validateAdventure(project).filter(i=>i.level==='error');if(errors.length){body.replaceChildren();const message=make('div',undefined,'player-empty');message.append(make('h2','No playable adventure yet'),make('p','The DM needs to add scene text, choices and an ending before this adventure is ready.'));const back=make('button','Return to DM mode','primary');back.onclick=()=>setMode('dm');message.append(back);body.append(message);}else{const playable=playerCopy(project);mountPlayer(body,playable,{edition:String(hash(JSON.stringify(playable).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029')))});}}}
$('dmMode').onclick=()=>setMode('dm');$('playerMode').onclick=()=>setMode('player');
$('blankExample').onclick=async()=>{await switchProject(newAdventure());setMode('dm');};
$('useExample').onclick=async()=>{const copy=structuredClone(project);copy.id=uid();copy.example=false;await switchProject(copy);setMode('dm');toast('Created an editable copy. The example remains in your library.');};

$('map').textContent='Flowchart';
$('dialog').addEventListener('close',()=>$('dialog').classList.remove('flow-dialog'));
$('map').onclick=()=>{const body=openDialog('Adventure flowchart');$('dialog').classList.add('flow-dialog');const toolbar=make('div',undefined,'flow-toolbar');const graphButton=make('button','Flowchart'),listButton=make('button','Text view'),save=make('button','Download SVG');const zoomLabel=make('label','Zoom');const zoom=make('input');zoom.type='range';zoom.min=25;zoom.max=150;zoom.value=100;zoom.setAttribute('aria-label','Flowchart zoom');zoomLabel.append(zoom);const fit=make('button','Fit');toolbar.append(graphButton,listButton,fit,zoomLabel,save);body.append(toolbar,make('p','Click a scene to edit it. Arrows show choices, checks and random events. Dashed red cards indicate missing destinations.','hint'));const viewport=make('div',undefined,'flow-viewport');viewport.tabIndex=0;viewport.setAttribute('aria-label','Scrollable adventure flowchart');body.append(viewport);let svg,width,height;
 const graph=()=>{viewport.replaceChildren();graphButton.setAttribute('aria-pressed','true');listButton.setAttribute('aria-pressed','false');viewport.classList.remove('flow-text');({svg,width,height}=drawFlowchart());viewport.append(svg);zoom.disabled=fit.disabled=save.disabled=false;scale();};
 const scale=()=>{if(svg){svg.style.width=width*Number(zoom.value)/100+'px';svg.style.height=height*Number(zoom.value)/100+'px';}};
 zoom.oninput=scale;fit.onclick=()=>{zoom.value=String(Math.max(25,Math.min(100,Math.floor(100*(viewport.clientWidth-24)/width))));scale();};graphButton.onclick=graph;listButton.onclick=()=>{viewport.replaceChildren();viewport.classList.add('flow-text');renderMapList(viewport);graphButton.setAttribute('aria-pressed','false');listButton.setAttribute('aria-pressed','true');zoom.disabled=fit.disabled=save.disabled=true;};save.onclick=()=>{const copy=svg.cloneNode(true);copy.removeAttribute('style');copy.setAttribute('width',width);copy.setAttribute('height',height);download(filename()+'-flowchart.svg',new XMLSerializer().serializeToString(copy),'image/svg+xml');};graph();requestAnimationFrame(()=>fit.click());};
function drawFlowchart(){
 const ns='http://www.w3.org/2000/svg',node=(tag,attrs={},text)=>{const n=document.createElementNS(ns,tag);for(const [key,value]of Object.entries(attrs))n.setAttribute(key,value);if(text!==undefined)n.textContent=text;return n;};
 const records=project.scenes.map(s=>({...s})),ids=new Set(records.map(s=>s.id)),edges=[];
 for(const s of project.scenes){if(s.ending)continue;s.choices.forEach((c,i)=>{const push=(target,label,type)=>{if(!ids.has(target)){const key=target||'missing-'+s.id+'-'+edges.length;if(!ids.has(key)){ids.add(key);records.push({id:key,title:'Missing destination',missing:true,choices:[]});}target=key;}edges.push({from:s.id,to:target,label,kind:type,number:i+1,check:c.type==='check'});};const prefix=(i+1)+'. '+(c.label||'Untitled choice');if(c.type==='random'){for(const e of c.events||[])push(e.target,prefix+' / d'+c.sides+' '+e.min+'–'+e.max+': '+e.label,'random');}else{push(c.target,prefix+(c.type==='check'?' / Success':''),'choice');if(c.type==='check')push(c.failure,prefix+' / Failure','failure');}});}
 const depth=new Map(),queue=[];if(ids.has(project.start)){depth.set(project.start,0);queue.push(project.start);}for(let i=0;i<queue.length;i++)for(const e of edges.filter(e=>e.from===queue[i]))if(!depth.has(e.to)){depth.set(e.to,depth.get(e.from)+1);queue.push(e.to);}
 const reachable=new Set(depth.keys());let last=Math.max(0,...depth.values());for(const r of records)if(!depth.has(r.id))depth.set(r.id,last+1);
 const rows=new Map();for(const r of records){const d=depth.get(r.id);if(!rows.has(d))rows.set(d,[]);rows.get(d).push(r);}
 const maxCols=Math.max(1,...[...rows.values()].map(r=>r.length)),width=maxCols*330+160,height=(Math.max(0,...depth.values())+1)*260+60;
 const svg=node('svg',{xmlns:ns,viewBox:'0 0 '+width+' '+height,role:'img','aria-label':'Scene flowchart for '+(project.title||'Untitled adventure')});svg.append(node('title',{},project.title||'Adventure flowchart'),node('rect',{width,height,fill:'#f8f8f0'}));const defs=node('defs');for(const [type,color]of [['choice','#628469'],['failure','#b15c49'],['random','#a98139']]){const marker=node('marker',{id:'arrow-'+type,viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:7,markerHeight:7,orient:'auto-start-reverse'});marker.append(node('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:color}));defs.append(marker);}svg.append(defs);
 const positions=new Map();for(const [d,row]of rows)row.forEach((r,i)=>positions.set(r.id,{x:60+i*330+(maxCols-row.length)*165,y:40+d*260}));
 edges.forEach((e,i)=>{const a=positions.get(e.from),b=positions.get(e.to),out=edges.filter(x=>x.from===e.from),slot=out.indexOf(e),startX=a.x+22+(slot+1)*196/(out.length+1),startY=a.y+96,endX=b.x+120,endY=b.y;let path,labelX,labelY;if(b.y>a.y){const mid=startY+55+(slot%3)*20;path='M '+startX+' '+startY+' V '+mid+' H '+endX+' V '+endY;labelX=(startX+endX)/2;labelY=mid-8;}else{const outside=Math.max(a.x,b.x)+260+(i%4)*14;path='M '+(a.x+240)+' '+(a.y+55)+' H '+outside+' V '+(b.y-20)+' H '+endX+' V '+endY;labelX=outside;labelY=b.y-28;}const color=e.kind==='failure'?'#b15c49':e.kind==='random'?'#a98139':'#628469';const g=node('g');g.append(node('title',{},e.label));g.append(node('path',{d:path,fill:'none',stroke:color,'stroke-width':2,'marker-end':'url(#arrow-'+e.kind+')'}));const short=e.kind==='failure'?'Choice '+e.number+' / Failure':e.kind==='random'?e.label.split(' / ').slice(-1)[0]:'Choice '+e.number+(e.check?' / Success':'');const label=short.length>30?short.slice(0,28)+'…':short;g.append(node('text',{x:labelX,y:labelY,'text-anchor':'middle',fill:color,'font-size':11,'font-family':'system-ui, sans-serif',stroke:'#f8f8f0','stroke-width':4,'paint-order':'stroke'},label));svg.append(g);});
 for(const r of records){const {x,y}=positions.get(r.id),start=r.id===project.start;const group=node('g',{'data-flow-scene':r.id});if(!r.missing){group.setAttribute('role','button');group.setAttribute('tabindex','0');group.setAttribute('aria-label','Edit scene: '+r.title);group.style.cursor='pointer';const edit=()=>{current=r.id;renderAll();$('dialog').close();$('sceneTitle').focus();};group.onclick=edit;group.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();edit();}};}group.append(node('title',{},r.title+(r.missing?'': '\n'+(r.ending?'Ending':r.choices.map((c,i)=>(i+1)+'. '+c.label).join('\n')))));
 group.append(node('rect',{x,y,width:240,height:96,rx:12,fill:r.missing?'#fff0e9':start?'#314c3e':r.ending?'#e5ecd8':'#fffef8',stroke:r.missing?'#b15c49':r.id===current?'#b58543':'#a6b49b','stroke-width':r.id===current?3:1.5,...(r.missing?{'stroke-dasharray':'6 4'}:{})}));group.append(node('text',{x:x+16,y:y+23,fill:start?'#dbe6d1':'#78866a','font-size':9,'font-family':'system-ui, sans-serif'},r.missing?'UNLINKED':!reachable.has(r.id)?'UNREACHABLE':start?'START':r.ending?'ENDING':'SCENE '+(project.scenes.findIndex(s=>s.id===r.id)+1)));
 const title=r.title||'Untitled scene',lines=title.match(/.{1,29}(?:\s|$)|.{1,29}/g)||[title];for(let i=0;i<Math.min(2,lines.length);i++)group.append(node('text',{x:x+16,y:y+48+i*19,fill:start?'#ffffff':'#2b4234','font-size':14,'font-family':'system-ui, sans-serif'},lines[i].trim()+(i===1&&lines.length>2?'…':'')));svg.append(group);}
 return {svg,width,height};
}


function renderSceneLoot(){const box=$('sceneLoot');box.replaceChildren();const scene=active();scene.loot??=[];if(!project.loot?.length){box.append(make('p','Add items to the loot list first. Then select what the player finds here.','hint'));return;}for(const item of project.loot){const row=make('div',undefined,'loot-award');const toggle=make('input');toggle.type='checkbox';const award=scene.loot.find(a=>a.itemId===item.id);toggle.checked=!!award;const label=field(item.name||'Untitled item',toggle);label.className='loot-toggle';const qty=make('input');qty.type='number';qty.min=1;qty.max=999;qty.value=award?.quantity||1;qty.disabled=!award;qty.setAttribute('aria-label','Quantity: '+item.name);toggle.onchange=()=>{checkpoint();scene.loot=scene.loot.filter(a=>a.itemId!==item.id);if(toggle.checked)scene.loot.push({itemId:item.id,quantity:1});changed();renderSceneLoot();};qty.onchange=()=>{checkpoint();const a=scene.loot.find(a=>a.itemId===item.id);if(a)a.quantity=Number(qty.value);changed();};row.append(label,qty);box.append(row);}}
function openLootCatalog(){const body=openDialog('Items, trinkets and loot');project.loot??=[];body.append(make('p','Build a reusable item list, then select rewards under Loot found in this scene. The ending lists collected items for the player to add to their character sheet.'));const name=make('input');name.placeholder='e.g. Brass compass';name.maxLength=200;const kind=make('select');for(const type of ['Item','Trinket','Treasure','Coin','Clue'])kind.append(new Option(type,type));const description=make('textarea');description.rows=2;description.placeholder='What it is and what it does';const fields=make('div',undefined,'loot-form');fields.append(field('Item name',name),field('Category',kind),field('Description',description));body.append(fields);const add=make('button','Add item','primary');add.onclick=()=>{if(!name.value.trim())return toast('Enter an item name.');if(project.loot.length>=200)return toast('The list supports 200 items.');checkpoint();project.loot.push({id:uid(),name:name.value.trim(),kind:kind.value,description:description.value});changed();renderSceneLoot();openLootCatalog();};body.append(add);
 const templates=make('details');templates.append(make('summary','Quick examples'));for(const [title,type,desc]of [['Brass compass','Trinket','An old compass with initials on its lid.'],['Handwritten map','Clue','A local map with a route marked in ink.'],['Silver brooch','Treasure','A small decorative brooch. Value is set by the DM.'],['Gold piece','Coin','One gold piece.'],['Repair kit','Item','A compact set of tools and spare parts.'],['Pressed flower','Trinket','A flower kept between folded pages.']]){const b=make('button',title);b.onclick=()=>{name.value=title;kind.value=type;description.value=desc;name.focus();};templates.append(b);}body.append(templates);
 const list=make('div');for(const item of project.loot){const row=make('div',undefined,'loot-entry');row.append(field('Name',inputFor(item,'name')),field('Description',inputFor(item,'description')));const category=make('select');for(const k of ['Item','Trinket','Treasure','Coin','Clue'])category.append(new Option(k,k));category.value=item.kind;category.onchange=()=>{checkpoint();item.kind=category.value;changed();};row.append(field('Category',category));const del=make('button','Delete item');del.onclick=()=>{const used=project.scenes.some(s=>s.loot?.some(a=>a.itemId===item.id));if(used&&!confirm('Remove this item from the list and all scene rewards?'))return;checkpoint();project.loot=project.loot.filter(i=>i.id!==item.id);for(const s of project.scenes)s.loot=(s.loot||[]).filter(a=>a.itemId!==item.id);changed();renderSceneLoot();openLootCatalog();};row.append(del);list.append(row);}body.append(list);}
$('lootCatalog').onclick=openLootCatalog;$('sceneLootCatalog').onclick=openLootCatalog;$('dialog').addEventListener('close',renderSceneLoot);
