function mountPlayer(root,adventure,options={}){
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const scenes=new Map(adventure.scenes.map(s=>[s.id,s]));
 const key='sidequest-play-'+adventure.id+'-'+(options.edition||'preview');
 const initial=()=>({scene:adventure.start,history:[],flags:[],notes:'',name:adventure.player||'',finished:false});let state=initial(),saveError='',runs=[];
 if(!options.preview)try{const value=JSON.parse(localStorage.getItem(key+'-runs')||'[]');if(Array.isArray(value))runs=value.filter(r=>typeof r.text==='string'&&typeof r.date==='string').slice(-20);}catch{}
 if(!options.preview)try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&scenes.has(saved.scene)&&Array.isArray(saved.history)&&Array.isArray(saved.flags))state={...initial(),...saved};}catch{}
 const save=()=>{if(!options.preview)try{localStorage.setItem(key,JSON.stringify(state));saveError='';}catch{saveError='Progress could not be saved in this browser. Download your recap before closing.';}};
 const download=(name,text)=>{const a=el('a');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 function collectedLoot(){const visited=new Set([...state.history.map(h=>h.from),state.scene]),totals=new Map();for(const id of visited)for(const award of scenes.get(id)?.loot||[]){const item=(adventure.loot||[]).find(i=>i.id===award.itemId);if(item&&Number.isInteger(award.quantity)&&award.quantity>0){const existing=totals.get(item.id)||{...item,quantity:0};existing.quantity+=award.quantity;totals.set(item.id,existing);}}return [...totals.values()];}
 function itemLines(){const items=collectedLoot();return ['ADD TO YOUR CHARACTER SHEET',...(items.length?items.map(i=>i.quantity+' × '+i.name+' ['+i.kind+']'+(i.description?' · '+i.description:'')):['No items to add.'])];}
 function showEndCard(){const ending=scenes.get(state.scene)?.ending,card=el('section',undefined,'loot-end-card');card.append(el('h2',ending?'Add to your character sheet':'Collected items'));const items=collectedLoot();for(const item of items){const row=el('div',undefined,'loot-item-row');row.append(el('strong',item.quantity+' × '+item.name),el('span',item.kind));if(item.description)row.append(el('p',item.description));card.append(row);}if(!items.length)card.append(el('p',ending?'No items to add.':'No items collected yet.'));const button=el('button','Download item list','player-primary');button.onclick=()=>download('Character-sheet-items.txt',[adventure.title,'PLAYER: '+(state.name||'Not supplied'),'ENDING: '+(ending?scenes.get(state.scene).title:'In progress'),'',...itemLines()].join('\n'));card.append(button);return card;}
 function recap(){const lines=[adventure.title,'PLAYER: '+(state.name||'Not supplied'),'STATUS: '+(scenes.get(state.scene)?.ending?'Reached an ending':'In progress'),'CURRENT SCENE: '+(scenes.get(state.scene)?.title||''),'','DECISIONS'];state.history.forEach((h,i)=>lines.push(`${i+1}. ${scenes.get(h.from)?.title||h.from} → ${h.label}${h.roll?.kind==='event'?' [d'+h.roll.sides+' = '+h.roll.die+' · '+h.roll.event+' · '+h.roll.source+']':h.roll?' [d20 '+h.roll.die+' + '+h.roll.modifier+' = '+h.roll.total+' vs DC '+h.roll.dc+' · '+(h.roll.success?'success':'failure')+' · '+h.roll.source+']':''}`));const ending=scenes.get(state.scene);if(ending?.ending)lines.push('','ENDING',ending.title,ending.reward||'');lines.push('',...itemLines(),'','STORY FLAGS',state.flags.join(', ')||'None','','PLAYER NOTES',state.notes||'None','','For DM review. Rewards and campaign consequences are not automatically approved.');return lines.join('\n');}
 function go(choice,roll){const target=roll?.kind==='event'?roll.target:roll&&!roll.success?choice.failure:choice.target;if(!scenes.has(target))return;state.history.push({from:state.scene,to:target,label:choice.label,roll,flags:[...state.flags]});if(choice.gives&&!state.flags.includes(choice.gives))state.flags.push(choice.gives);state.scene=target;state.finished=false;save();render();root.scrollIntoView({block:'start',behavior:'smooth'});}
 function rollCheck(choice,box){box.replaceChildren();box.append(el('p',(choice.skill||'Ability')+' check · DC '+choice.dc));const label=el('label','Your modifier');const modifier=el('input');modifier.type='number';modifier.min='-30';modifier.max='30';modifier.value=String(choice.modifier||0);label.append(modifier);box.append(label);const manualLabel=el('label','Or enter your physical d20 result');const manual=el('input');manual.type='number';manual.min='1';manual.max='20';manual.placeholder='1–20';manualLabel.append(manual);box.append(manualLabel);const error=el('p','','player-error');error.setAttribute('role','status');const actions=el('div',undefined,'player-actions');
 const finish=(die,source)=>{const mod=Number(modifier.value);if(!Number.isInteger(mod)||Math.abs(mod)>30||modifier.value===''){error.textContent='Enter a modifier from −30 to 30.';return;}if(!Number.isInteger(die)||die<1||die>20){error.textContent='Enter a d20 result from 1 to 20.';return;}const total=die+mod,success=total>=choice.dc;actions.replaceChildren();modifier.disabled=true;manual.disabled=true;error.textContent=`${die} + ${mod} = ${total}. ${success?'Success':'Failure'}!`;const next=el('button','Continue','player-primary');next.onclick=()=>go(choice,{die,modifier:mod,total,dc:choice.dc,success,source});actions.append(next);};
 const random=el('button','Roll a d20','player-primary');random.onclick=()=>{const numbers=new Uint32Array(1);do{crypto.getRandomValues(numbers);}while(numbers[0]>=4294967280);finish(numbers[0]%20+1,'app roll');};const use=el('button','Use my roll');use.onclick=()=>finish(Number(manual.value),'player-entered roll');const cancel=el('button','Cancel');cancel.onclick=render;actions.append(random,use,cancel);box.append(error,actions);}
 function validEventTable(c){if(![4,6,8,10,12,20,100].includes(c.sides)||!c.events?.length)return false;for(const e of c.events)if(!Number.isInteger(e.min)||!Number.isInteger(e.max)||e.min<1||e.max>c.sides||e.min>e.max||!e.label?.trim()||!scenes.has(e.target))return false;for(let die=1;die<=c.sides;die++)if(c.events.filter(e=>e.min<=die&&e.max>=die).length!==1)return false;return true;}
 function rollEvent(choice,box){box.replaceChildren();box.append(el('p','Random event · d'+choice.sides));const label=el('label','Physical die result (optional)'),input=el('input');input.type='number';input.min=1;input.max=choice.sides;label.append(input);box.append(label);const result=el('p','','event-result');result.setAttribute('role','status');const actions=el('div',undefined,'player-actions');let rolled=false;const finish=(die,source)=>{if(rolled)return;if(!Number.isInteger(die)||die<1||die>choice.sides){result.textContent='Enter a result from 1 to '+choice.sides+'.';return;}const event=choice.events.find(e=>e.min<=die&&e.max>=die);if(!event||!scenes.has(event.target)){result.textContent='This roll has no valid event. Ask your DM to fix the table.';return;}rolled=true;input.disabled=true;result.textContent='Rolled '+die+': '+event.label;actions.replaceChildren();const next=el('button','Continue','player-primary');next.onclick=()=>go(choice,{kind:'event',sides:choice.sides,die,event:event.label,target:event.target,source});actions.append(next);};const roll=el('button','Roll d'+choice.sides,'player-primary');roll.onclick=()=>{const n=new Uint32Array(1),limit=Math.floor(4294967296/choice.sides)*choice.sides;do{crypto.getRandomValues(n);}while(n[0]>=limit);finish(n[0]%choice.sides+1,'app roll');};const physical=el('button','Use my result');physical.onclick=()=>finish(Number(input.value),'player-entered roll');const cancel=el('button','Cancel');cancel.onclick=render;actions.append(roll,physical,cancel);box.append(result,actions);}
 function render(){root.replaceChildren();root.classList.add('player-root');const s=scenes.get(state.scene);if(!s){root.append(el('p','This scene is missing. Ask your DM for an updated adventure.'));return;}if(adventure.example)root.append(el('p','EXAMPLE ADVENTURE: Placeholder content for learning the app. This is not an assigned campaign session.','example-player'));const top=el('div',undefined,'player-top');top.append(el('span',options.preview?'PLAYER PREVIEW':'SIDEQUEST / PLAYER VIEW'));const tools=el('div',undefined,'player-actions');const reset=el('button','Replay');reset.onclick=()=>{if(confirm('Start a new playthrough? This run’s recap will be kept in Previous runs.')){if(state.history.length||state.notes){runs.push({date:new Date().toISOString(),text:recap()});runs=runs.slice(-20);if(!options.preview)try{localStorage.setItem(key+'-runs',JSON.stringify(runs));}catch{download('Previous-adventure-recap.txt',recap());}}state=initial();save();render();}};const exportButton=el('button','Download recap');exportButton.onclick=()=>download('Adventure-recap.txt',recap());tools.append(exportButton,reset);top.append(tools);root.append(top,el('h1',adventure.title),el('p',adventure.subtitle,'player-subtitle'));
 if(!state.history.length&&adventure.briefing){const brief=el('details');brief.open=true;brief.append(el('summary','Before you begin'),el('p',adventure.briefing,'story-text'));root.append(brief);}
 const article=el('article',undefined,'player-scene');if(s.image){const img=el('img');img.src=s.image;img.alt=s.alt||'';img.className='player-image';article.append(img);}article.append(el('span',s.ending?'THE END':'SCENE','player-kicker'),el('h2',s.title),el('div',s.body,'story-text'));if(s.ending){if(s.reward)article.append(el('div',s.reward,'player-reward'));article.append(el('p','Your DM will review this outcome. Download your recap and send it back when you’re ready.'));const done=el('button','Download my adventure recap','player-primary');done.onclick=()=>download('Adventure-recap.txt',recap());article.append(done);}else{const choices=el('div',undefined,'player-choices');let available=0;for(const c of s.choices){if(c.requires&&!state.flags.includes(c.requires))continue;available++;const button=el('button',c.label+(c.type==='check'?' · '+(c.skill||'Ability')+' check':c.type==='random'?' · roll d'+c.sides:''),'player-choice');button.disabled=c.type==='random'?!validEventTable(c):!scenes.has(c.target)||(c.type==='check'&&!scenes.has(c.failure));button.onclick=()=>{if(c.type==='random'){rollEvent(c,choices);}else if(c.type==='check'){choices.replaceChildren();rollCheck(c,choices);}else go(c,null);};choices.append(button);}if(!available)choices.append(el('p','No available choices. Go back or ask your DM to revise this scene.'));article.append(choices);}root.append(article);if(s.ending)root.append(showEndCard());else if((adventure.loot||[]).length){const inventory=el('details');inventory.append(el('summary','Inventory · '+collectedLoot().reduce((sum,i)=>sum+i.quantity,0)+' items'),showEndCard());root.append(inventory);}
 const notes=el('details');notes.append(el('summary','Your notes & character name'));const nameLabel=el('label','Character / player');const name=el('input');name.value=state.name;name.maxLength=100;name.oninput=()=>{state.name=name.value;save();};nameLabel.append(name);const noteLabel=el('label','What would you like your DM to know?');const text=el('textarea');text.rows=5;text.value=state.notes;text.maxLength=50000;text.oninput=()=>{state.notes=text.value;save();};noteLabel.append(text);notes.append(nameLabel,noteLabel);root.append(notes);const bottom=el('div',undefined,'player-bottom');if(state.history.length){const back=el('button','← Undo last choice');back.onclick=()=>{const h=state.history.pop();state.scene=h.from;state.flags=h.flags;save();render();};bottom.append(back);}bottom.append(el('span',options.preview?'Preview progress is separate from the player’s adventure.':saveError||'Progress saves in this browser. Keep using the same file and browser.'));root.append(bottom);if(runs.length){const archive=el('details');archive.append(el('summary','Previous runs · '+runs.length));for(const run of [...runs].reverse()){const row=el('div',undefined,'player-actions');const title=el('span',new Date(run.date).toLocaleString());const button=el('button','Download this recap');button.onclick=()=>download('Previous-adventure-recap.txt',run.text);row.append(title,button);archive.append(row);}root.append(archive);}if(saveError)bottom.setAttribute('role','alert');
 }
 render();return {reset(){state=initial();render();},recap};
}
